/*
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 *
*/
#include<iostream>
#include<string>
#include<cmath>
#include<stdlib.h>
using namespace std;


int main(){

	int count = 2; 
	int last_one = 1;
	int last_two = 2;
  int i = last_one +last_two;
	while (i < 4000000){
		if (i%2 == 0)
			count += i;
    last_one = last_two;
    last_two = i;
    i = last_one +last_two;
	}

	cout << count << endl;

	return 0;
}

